ARCHS = armv7

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = TCBiOS56
TCBiOS56_FILES = Tweak.xm
TCBiOS56_FRAMEWORKS = UIKit
TCBiOS56_INSTALL_PATH = /Library/Application Support/TCB
TCBiOS56_LIBRARIES = substrate

include $(THEOS_MAKE_PATH)/library.mk
