TARGET = iphone:latest:7.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = TCBiOS7
TCBiOS7_FILES = Tweak.xm
TCBiOS7_FRAMEWORKS = UIKit
TCBiOS7_INSTALL_PATH = /Library/Application Support/TCB
TCBiOS7_LIBRARIES = substrate

include $(THEOS_MAKE_PATH)/library.mk
